name: apple-music-for-linux
version: '0.2'
summary: Apple Music for Linux
description: Apple Music for Linux

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/zenity:
    bind: $SNAP/usr/share/zenity

parts:
  chromium:
    source: dump
    plugin: dump
    stage-packages:
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - unzip
      - wget
      - zenity

  cleanup:
      after: [ chromium ]
      plugin: nil
      build-snaps:
          - core18
          - gnome-3-28-1804
          - gtk-common-themes
      override-prime: |
          set -eux
          cd /snap/core18/current
          find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
          cd /snap/gnome-3-28-1804/current
          find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
          cd /snap/gtk-common-themes/current
          find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/{} \;

apps:
  apple-music-for-linux:
    command: apple-music-for-linux.launcher
    extensions: [gnome-3-28]
    plugs:
      - audio-playback
      - browser-support
      - network
    environment:
      DISABLE_WAYLAND: 1
